version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: rfdata
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password12
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
